In [19]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [20]:
# Concantanate enables two dataframes to be joined together
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# concatenating arrays
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [22]:
np.concatenate([arr1, arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
ser1 = Series([0,1,2], index=['t', 'u', 'x'])
ser2 = Series([3,4], index=['x','y'])

In [24]:
ser1

t    0
u    1
x    2
dtype: int64

In [25]:
ser2

x    3
y    4
dtype: int64

In [26]:
pd.concat([ser1,ser2])

t    0
u    1
x    2
x    3
y    4
dtype: int64

In [27]:
# creates data frame because 1st series doesnt have x,y info and 2nd series doesn't have t,u,v info
pd.concat([ser1,ser2], axis=1)

0    1
t  0.0  NaN
u  1.0  NaN
x  2.0  3.0
y  NaN  4.0

In [28]:
# combine with a hierarchial index
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  t    0
      u    1
      x    2
cat2  x    3
      y    4
dtype: int64

In [29]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['x','y','z'])
dframe1

x         y         z
0 -0.251252 -0.472775 -0.656128
1  0.276176  0.616824  0.307846
2  1.327199 -0.997681 -0.803391
3  1.081707 -0.287157  0.524253

In [30]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['y','q','x'])
dframe2

y         q         x
0 -1.447810  0.388739 -0.150280
1  0.601415 -0.574949 -0.533172
2 -0.522740 -0.170410 -0.084585

In [31]:
# kept index information when concatenationg (note 0,1,2 are repeated)
pd.concat([dframe1, dframe2])

q         x         y         z
0       NaN -0.251252 -0.472775 -0.656128
1       NaN  0.276176  0.616824  0.307846
2       NaN  1.327199 -0.997681 -0.803391
3       NaN  1.081707 -0.287157  0.524253
0  0.388739 -0.150280 -1.447810       NaN
1 -0.574949 -0.533172  0.601415       NaN
2 -0.170410 -0.084585 -0.522740       NaN

In [32]:
# can ignore index info if we don't care about it and want a continuous, UNIQUE index
pd.concat([dframe1, dframe2], ignore_index=True)


q         x         y         z
0       NaN -0.251252 -0.472775 -0.656128
1       NaN  0.276176  0.616824  0.307846
2       NaN  1.327199 -0.997681 -0.803391
3       NaN  1.081707 -0.287157  0.524253
4  0.388739 -0.150280 -1.447810       NaN
5 -0.574949 -0.533172  0.601415       NaN
6 -0.170410 -0.084585 -0.522740       NaN

In [33]:
url = 'http://pandas.pydata.org/pandas-docs-/dev/generated/pandas.tools.merge.concat.html'

In [35]:
pd.concat([dframe1,dframe2],axis=1)

x         y         z         y         q         x
0 -0.251252 -0.472775 -0.656128 -1.447810  0.388739 -0.150280
1  0.276176  0.616824  0.307846  0.601415 -0.574949 -0.533172
2  1.327199 -0.997681 -0.803391 -0.522740 -0.170410 -0.084585
3  1.081707 -0.287157  0.524253       NaN       NaN       NaN