In [1]:
import numpy as np

In [3]:
# universal array functions are functions that can map over every value in the array
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
# e (eulers constant) to the power of each value in the array
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
a = np.random.randn(10)
a

array([ 1.57115609,  2.10286428, -1.31774172,  1.61541226, -0.52370913,
        0.35200619, -3.44108038, -1.84349705,  0.46732051,  0.96492571])

In [9]:
b = np.random.randn(10)
b

array([-0.7766476 ,  0.3422842 , -0.43718335,  0.45246446, -0.43137251,
       -1.51703409,  1.83060484, -0.82169343, -0.86700449,  0.91501682])

In [10]:
# binary functions, use 2 arrays
np.add(a,b)

array([ 0.79450848,  2.44514849, -1.75492507,  2.06787672, -0.95508164,
       -1.1650279 , -1.61047554, -2.66519048, -0.39968398,  1.87994253])

In [11]:
np.maximum(a,b)

array([ 1.57115609,  2.10286428, -0.43718335,  1.61541226, -0.43137251,
        0.35200619,  1.83060484, -0.82169343,  0.46732051,  0.96492571])