In [2]:
# this notebook deals with saving and opening arrays
import numpy as np


In [4]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [5]:
# save array
np.save('myarray',arr)

In [6]:
# overwrite existing array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# load saved array. Saved arrays have the extension '.npy'
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [9]:

arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# save both arrays
np.savez('ziparray.npz', x=arr1, y=arr2)

In [16]:
# loading multiple arrays
archive_arr = np.load('ziparray.npz')
archive_arr

In [14]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# save array as a .txt file
np.savetxt('mytextarray', arr,delimiter=',')

In [29]:
arr = np.loadtxt('mytextarray', delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])