In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# slice is a view of the parent array from which it is created. This implementation preserves memory usage
slice_arr = arr[0:5]

In [5]:
slice_arr

array([0, 1, 2, 3, 4])

In [8]:

slice_arr[:] = 99

In [7]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [9]:
# to make a separate copy of an array
arr_copy = arr.copy()

In [13]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,45,55]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 45, 55]])

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 45, 55]])

In [14]:
# view row using row index
arr_2d[1]

array([20, 25, 30])

In [15]:
arr_2d[1][0]

20

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 45, 55]])

In [28]:
# get 2x2 array from top-right corner, "all rows before the second indexed row and all colums after the first
# indexed column"
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr2d = np.zeros((10,10))
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [32]:
# get length of array
arr_length = arr2d.shape[1]
arr_length

10

In [33]:
for i in range(arr_length):
  arr2d[i] = i

In [35]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [36]:
# fancy indexing, can select multiple row indexes in any order
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])