In [1]:
import numpy as np

In [2]:
mylist1 = [1,2,3]

In [3]:
myarray1 = np.array(mylist1)

In [4]:
myarray1

array([1, 2, 3])

In [5]:
mylist2 = [22,23,24]

In [6]:
mylists = [mylist1, mylist2]

In [7]:
mylists

[[1, 2, 3], [22, 23, 24]]

In [9]:
myarray2 = np.array(mylists)

In [10]:
myarray2


array([[ 1,  2,  3],
       [22, 23, 24]])

In [11]:
myarray2.shape

(2, 3)

In [13]:
myarray2.dtype

dtype('int64')

In [17]:
zeros_array = np.zeros(5)

In [16]:
zeros_array.dtype

dtype('float64')

In [21]:
ones_array = np.ones([5,5])

In [19]:
ones_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
np.empty

<function numpy.core.multiarray.empty>

In [23]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
# identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
# start at 5, stop at 50 and intervals of 2 between values in array to be created
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])