In [1]:
import numpy as np

In [8]:
arr = np.arange(0,12)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[8]

8

In [16]:
# gets values in index range 1 inclusive to 5 exclusive
arr[1:5]

array([1, 2, 3, 4])

In [17]:
arr[0:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11])

In [19]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [27]:
# use : to select all elements in the array
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])